preferred_syntax = :ssss
http_path = '/'
css_dir = '/'
sass_dir = 'sass'
images_dir = 'images'
javascripts_dir = 'js'
relative_assets = true
line_comments = true
output_style = :compressed
sourcemap = false # by Compass.app 